name: rxa_flutter_kit
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.17.3 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  get: ^4.6.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true